image: "crystallang/crystal:latest"

# Cache shards in between builds
cache:
  paths:
    - lib

# This is a basic example for a shard or script which doesn't use
# services such as redis or postgres
before_script:
  - apt-get update -qq && apt-get install -y -qq libxml2-dev
  - crystal -v # Print out Crystal version for debugging
  - shards

# If you are using built-in Crystal Spec.
spec:
  script:
  - crystal spec
